# Generated by Django 4.2.13 on 2024-06-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEP',
            fields=[
                ('mep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
                ('hometown', models.CharField(max_length=58, null=True)),
                ('country_of_representation', models.CharField(max_length=3, null=True)),
                ('combined_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalGroup',
            fields=[
                ('group', models.CharField(max_length=89, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.CharField(max_length=250)),
                ('label', models.TextField(default='Unknown')),
                ('date', models.DateField()),
                ('outcome', models.CharField(max_length=50, null=True)),
                ('number_of_votes', models.IntegerField()),
                ('number_of_abstentions', models.IntegerField()),
                ('number_of_yes', models.IntegerField()),
                ('number_of_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=255)),
                ('mep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mep')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vote_info')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.politicalgroup')),
                ('mep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mep')),
            ],
        ),
    ]
