# Generated by Django 5.0.4 on 2024-07-01 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MEP",
            fields=[
                ("mep_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=100, null=True)),
                ("gender", models.CharField(max_length=6, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("date_of_death", models.DateField(null=True)),
                ("hometown", models.CharField(max_length=58, null=True)),
                (
                    "country_of_representation",
                    models.CharField(max_length=3, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliticalGroup",
            fields=[
                (
                    "group",
                    models.CharField(max_length=89, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteInfo",
            fields=[
                (
                    "vote_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20, null=True)),
                (
                    "interinstitutional_file_no",
                    models.CharField(max_length=15, null=True),
                ),
                ("label", models.TextField(default="N/A", null=True)),
                ("date", models.DateField()),
                ("caller", models.CharField(max_length=109, null=True)),
                ("rapporteur", models.CharField(max_length=255, null=True)),
                ("committee_responsible", models.CharField(max_length=119, null=True)),
                ("main_policy_issue", models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "mep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.mep"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.politicalgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_type", models.CharField(max_length=255)),
                (
                    "mep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.mep"
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.voteinfo"
                    ),
                ),
            ],
        ),
    ]
