# Generated by Django 4.2.13 on 2024-05-30 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=255, unique=True)),
                ('activity_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MEP',
            fields=[
                ('unique_identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
                ('hometown', models.CharField(max_length=58, null=True)),
                ('country_of_representation', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalGroup',
            fields=[
                ('group', models.CharField(max_length=89, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=250)),
                ('outcome', models.CharField(max_length=50)),
                ('number_of_attendees', models.IntegerField()),
                ('number_of_favor', models.IntegerField()),
                ('number_of_against', models.IntegerField()),
                ('number_of_abstention', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MEPVoteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=50)),
                ('mep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mep')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vote')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.politicalgroup')),
                ('mep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mep')),
            ],
        ),
    ]
