# Generated by Django 4.2.13 on 2024-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mep',
            name='political_party',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mep_vote_mapping',
            name='choice',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
