# Generated by Django 5.0.4 on 2024-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mep_vote_mapping",
            name="vote_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="number_of_not_voted",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="mep_vote_mapping",
            unique_together={("mep", "vote", "vote_type")},
        ),
    ]
