# Generated by Django 4.2.13 on 2024-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='vote_info',
            name='vote_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
