# Generated by Django 4.2.14 on 2024-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mep',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
