# Generated by Django 5.0.4 on 2024-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_mep_vote_mapping_vote_type_vote_number_of_not_voted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="label",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="vote",
            name="unique_identifier",
            field=models.CharField(max_length=500),
        ),
    ]
