# Generated by Django 4.2.13 on 2024-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mep_political_party_mep_vote_mapping_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mep',
            name='unique_identifier',
            field=models.IntegerField(unique=True),
        ),
    ]
