# Generated by Django 4.2.13 on 2024-06-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vote_info_id_alter_vote_info_vote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteInfo',
            fields=[
                ('vote_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('label', models.TextField(default='Unknown')),
                ('date', models.DateField()),
                ('caller', models.CharField(max_length=50)),
                ('outcome', models.CharField(max_length=50, null=True)),
                ('number_of_votes', models.IntegerField()),
                ('number_of_abstentions', models.IntegerField()),
                ('number_of_yes', models.IntegerField()),
                ('number_of_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='votemapping',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voteinfo'),
        ),
        migrations.DeleteModel(
            name='Vote_info',
        ),
    ]
