# Generated by Django 5.0.4 on 2024-05-24 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_vote_label_alter_vote_unique_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="label",
        ),
    ]
