# Generated by Django 4.2.13 on 2024-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_voteinfo_alter_votemapping_vote_delete_vote_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='caller',
            field=models.CharField(max_length=100),
        ),
    ]
