# Generated by Django 4.2.13 on 2024-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_voteinfo_caller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='caller',
            field=models.CharField(max_length=200),
        ),
    ]
