# Generated by Django 4.2.13 on 2024-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_voteinfo_caller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='number_of_abstentions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='number_of_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='number_of_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='number_of_yes',
            field=models.IntegerField(null=True),
        ),
    ]
