# Generated by Django 4.2.13 on 2024-06-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_voteinfo_number_of_abstentions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteinfo',
            name='number_of_votes',
        ),
        migrations.RemoveField(
            model_name='voteinfo',
            name='outcome',
        ),
    ]
