# Generated by Django 4.2.13 on 2024-06-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_voteinfo_number_of_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='caller',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
