# Generated by Django 4.2.13 on 2024-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_voteinfo_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteinfo',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='committee_responsible',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='interinstitutional_file_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='main_policy_issue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='rapporteur',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
