# Generated by Django 4.2.13 on 2024-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_voteinfo_code_voteinfo_committee_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='caller',
            field=models.CharField(max_length=109, null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='committee_responsible',
            field=models.CharField(max_length=119, null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='interinstitutional_file_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='main_policy_issue',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='rapporteur',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
