# Generated by Django 4.2.13 on 2024-06-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_voteinfo_caller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='label',
            field=models.TextField(default='N/A', null=True),
        ),
    ]
