# Generated by Django 4.2.13 on 2024-06-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_voteinfo_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteinfo',
            name='number_of_abstentions',
        ),
        migrations.RemoveField(
            model_name='voteinfo',
            name='number_of_no',
        ),
        migrations.RemoveField(
            model_name='voteinfo',
            name='number_of_yes',
        ),
    ]
