# Generated by Django 4.2.13 on 2024-06-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_voteinfo_number_of_abstentions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mep',
            old_name='combined_name',
            new_name='full_name',
        ),
    ]
